Added dependencies for initial migration
  Sometimes south could not resolved dependencies properly. So I tried add
them manualy. For now it depends on attachments migration and fixed next
error messages:
>> django.db.utils.DatabaseError: relation "attachments_attachment"
>> does not exist